{% set name = "cxxopts" %}
{% set version = "3.2.1" %}
{% set sha256 = "841f49f2e045b9c6365997c2a8fbf76e6f215042dda4511a5bb04bc5ebc7f88a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jarro2783/cxxopts/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]
  # The cxxopts library is header only, so we do not need
  # to export the compiler run-time libraries.
  # They are just needed during the build to perform some checks.
  ignore_run_exports_from:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}

requirements:
  build:
    - cmake
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/cxxopts.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config-version.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\cxxopts.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cxxopts-config.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cxxopts-config-version.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jarro2783/cxxopts
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight C++ option parser library
  description: This is a lightweight C++ option parser library, supporting the standard GNU style syntax for options.
  doc_url: https://github.com/jarro2783/cxxopts
  dev_url: https://github.com/jarro2783/cxxopts

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
