{% set name = "cxxopts" %}
{% set version = "2.1.1" %}
{% set sha256 = "e19216251427d04f0273e6487c0246ae2dbb4154bf178f43896af8fa1ef89f3f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jarro2783/cxxopts/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win and vc<14]
  # The cxxopts library is header only, so we do not need
  # to export the compiler run-time libraries.
  # They are just needed during the build to perform some checks.
  ignore_run_exports:
    - libcxx
    - libgcc-ng
    - libstdcxx-ng
    - vc
    - vs2015_runtime

requirements:
  host: []
  build:
    - cmake
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/include/cxxopts.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config-version.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\cxxopts.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cxxopts-config.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cxxopts-config-version.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jarro2783/cxxopts
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A lightweight C++ option parser library'
  description: 'This is a lightweight C++ option parser library, supporting the standard GNU style syntax for options.'
  doc_url: https://github.com/jarro2783/cxxopts
  dev_url: https://github.com/jarro2783/cxxopts

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
