{% set name = "cxxopts" %}
{% set version = "1.4.1" %}
{% set sha256 = "c5ccfe99bd3db0604d077c968b39a42d61333a64d171fe84d7037d6c0dcc996d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jarro2783/cxxopts/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -f ${PREFIX}/include/cxxopts.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config-version.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\cxxopts.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cxxopts-config.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cxxopts-config-version.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jarro2783/cxxopts
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A lightweight C++ option parser library'
  description: 'This is a lightweight C++ option parser library, supporting the standard GNU style syntax for options.'
  doc_url: https://github.com/jarro2783/cxxopts
  dev_url: https://github.com/jarro2783/cxxopts

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
