{% set name = "cxxopts" %}
{% set version = "2.1.0" %}
{% set sha256 = "7672c79e5e48dd0cb1935c6efe65d2695d96fa764bf06c493d2db25a3cf633b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jarro2783/cxxopts/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patch:
    - 0001-Fixup-integer-pattern-multiple-definition.patch

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -f ${PREFIX}/include/cxxopts.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/cxxopts/cxxopts-config-version.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\cxxopts.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cxxopts-config.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cxxopts-config-version.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/jarro2783/cxxopts
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A lightweight C++ option parser library'
  description: 'This is a lightweight C++ option parser library, supporting the standard GNU style syntax for options.'
  doc_url: https://github.com/jarro2783/cxxopts
  dev_url: https://github.com/jarro2783/cxxopts

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
